apiVersion: v1
kind: Service
metadata:
  name: movie-catalog
  labels:
    name: movie-catalog
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: movie-catalog
  type: LoadBalancer
