movie-info:
ratings-data:

server:
  port: 8081

spring:
  application:
    name: movie-catalog
  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8095/eureka/
    healthcheck:
      enabled: true