server:
  port: 8080

spring:
  application:
    name: movie-catalog

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server/eureka/
    healthcheck:
      enabled: true

#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream